[project]
name = "dmypy_final_bug"
version = "0.1.0"
description = "dmypy bug"
authors = [{ name = "Randolf Scholz", email = "randolf.scholz@gmail.com" }]
dependencies = ["torch==2.4.0", "mypy==1.11.1"]
requires-python = "==3.12.*"
readme = "README.md"
license = { text = "MIT" }
